" Author: Jonathan Catanio
" Description: Global settings for all files (may be overriden by ftplugin)

" Start vim-plug code
call plug#begin('~/.vim/plugged')

Plug 'morhetz/gruvbox'                     " Gruvbox color scheme
Plug 'tpope/vim-fugitive'                  " Git wrapper for vim
Plug 'vim-airline/vim-airline'             " Lightweight status/tabline
Plug 'vim-airline/vim-airline-themes'      " Themes for vim-airline
"Plug 'scrooloose/syntastic'               " Syntax checking
Plug 'scrooloose/nerdtree'                 " Filesystem tree explorer
Plug 'jiangmiao/auto-pairs'                " Completes character pairs
Plug 'rust-lang/rust.vim', {'for': 'rust'} " Rust file detection and more
Plug 'pangloss/vim-javascript'             " JS indentation/syntax support
Plug 'mxw/vim-jsx'                         " JSX syntax highlighting

" Initialize plugin system
call plug#end()

" vim-plug sets filetype, plugin, and indent; turn off indent
" filetype indent off

" Custom VIM settings
set title          " change the terminal title

set laststatus=2   " Show status line
set number         " Show line number on cursor
set relativenumber " Show relative line numbers
set mouse=a        " Enable mouse

syntax on          " Enable syntax highlighting
colorscheme gruvbox

set nowrap         " Lines don't wrap
set expandtab      " Tabs become spaces
set shiftwidth=4   " Shifts only shift three spaces
set softtabstop=0  " If non-zero, makes the <TAB> & <BS> keys feel like tabs
set tabstop=3      " Tabs stop at three characters
set backspace=indent,eol,start " Backspace over everything in insert mode
set autoindent     " Auto indent
set copyindent     " Use last line indentation, affects <BR> key
set smarttab       " Insert new line tabs based on shiftwidth not tabstop

set ruler          " Shows the ruler at the bottom of the window
set colorcolumn=80 " Draws column at 80 characters

set hlsearch       " Highlight search terms
set incsearch      " Highlight incrementally while searching

set wildignore=*.swp,*.bak,*.pyc,*.class,*.o " Don't auto-complete these files

" List will mark any characters specified by `listchars`
set list
set listchars=tab:\ \ ,trail:·,extends:▶

" File specific settings, most should be moved into after/ or ftplugin/
autocmd filetype make set tabstop=3 shiftwidth=3 softtabstop=0 noexpandtab

" Custom Plugin settings
" vim-airline settings
let g:airline_theme='gruvbox'
let g:airline#extensions#tabline#enabled=1
"let g:airline#extensions#syntastic#enabled=1
let g:airline_powerline_fonts=1 " Make sure powerline fonts are installed

" syntastic
"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 0
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0
"let g:syntastic_error_symbol = "➤"
"hi SyntasticError       ctermfg=231 ctermbg=226
"hi SyntasticWarning     ctermfg=231 ctermbg=226
"hi SyntasticErrorSign   ctermfg=123 ctermbg=123
"hi SyntasticWarningSign ctermfg=123 ctermbg=123

" Open markdown files with Chrome.
autocmd BufEnter *.md exe 'noremap <F5> :! /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome %:p<CR>'
