#!/bin/sh

# Set up vim links.
ln -s ~/dotfiles/vim/vimrc ~/.vimrc
mkdir -p ~/.vim/colors
ln -s ~/dotfiles/vim/colors/molokai.vim ~/.vim/colors/molokai.vim

# Setup necessary .vim directories if they don't exist.
mkdir -p ~/.vim/syntax
mkdir -p ~/.vim/ftdetect
mkdir -p ~/.vim/after/ftplugin

# Set up CoffeeScript syntax highlighting for vim.
ln -s ~/dotfiles/vim/syntax/coffee.vim ~/.vim/syntax/coffee.vim
ln -s ~/dotfiles/vim/ftdetect/coffee.vim ~/.vim/ftdetect/coffee.vim

# Set up Python overriding features
ln -s ~/dotfiles/vim/after/ftplugin/python.vim ~/.vim/after/ftplugin/python.vim

# Set up bash links.
ln -s ~/dotfiles/bash/bash_profile ~/.bash_profile
ln -s ~/dotfiles/bash/bashrc ~/.bashrc

# For Arch Linux session configuration link.
ln -s ~/dotfiles/bash/profile ~/.xprofile

# NOTE: These aren't necessary for Mac OS X, comment out.
ln -s ~/dotfiles/bash/DIR_COLORS ~/.dir_colors
ln -s ~/dotfiles/bash/Xresources ~/.Xresources
