#!/bin/sh

# Vim: Set up environment
ln -s ~/dotfiles/vim/vimrc ~/.vimrc

# Vim: Setup necessary .vim directories if they don't exist.
mkdir -p ~/.vim/syntax
mkdir -p ~/.vim/ftdetect
mkdir -p ~/.vim/after/ftplugin
mkdir -p ~/.vim/autoload

# Vim: Set up CoffeeScript syntax highlighting for vim.
ln -s ~/dotfiles/vim/syntax/coffee.vim ~/.vim/syntax/coffee.vim
ln -s ~/dotfiles/vim/ftdetect/coffee.vim ~/.vim/ftdetect/coffee.vim

# Vim: Set up Python overriding features
ln -s ~/dotfiles/vim/after/ftplugin/python.vim ~/.vim/after/ftplugin/python.vim

# Vim: Install plugin manager
curl -fLo ~/dotfiles/vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
ln -s ~/dotfiles/vim/autoload/plug.vim ~/.vim/autoload/plug.vim

# Bash: Set up bash links.
ln -s ~/dotfiles/bash/bash_profile ~/.bash_profile
ln -s ~/dotfiles/bash/bashrc ~/.bashrc

# ZSH: Set up ZSH links.
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
curl -o - https://raw.githubusercontent.com/denysdovhan/spaceship-zsh-theme/master/install.zsh | zsh
ln -s ~/dotfiles/zsh/zshrc ~/.zshrc

# Distribution specific setup
if [[ "$OSTYPE" == "darwin"* ]]; then # MacOS
   # Install Homebrew
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
   brew update
   brew install screenfetch fortune cowsay lolcat
elif [[ "$OSTYPE" == "linux-gnu" ]]; then # Linux
   ln -s ~/dotfiles/bash/DIR_COLORS ~/.dir_colors
   ln -s ~/dotfiles/bash/Xresources ~/.Xresources
fi
