#!/bin/sh

# Vim: Set up environment
ln -s ~/dotfiles/vim/vimrc ~/.vimrc

# Vim: Setup necessary .vim directories if they don't exist.
mkdir -p ~/.vim/syntax
mkdir -p ~/.vim/ftdetect
mkdir -p ~/.vim/after/ftplugin
mkdir -p ~/.vim/autoload

# Vim: Install plugin manager
curl -fLo ~/dotfiles/vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
ln -s ~/dotfiles/vim/autoload/plug.vim ~/.vim/autoload/plug.vim

# Bash: Set up bash links.
ln -s ~/dotfiles/bash/bash_profile ~/.bash_profile
ln -s ~/dotfiles/bash/bashrc ~/.bashrc

# ZSH: Set up ZSH links.
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme" 
ln -s ~/dotfiles/zsh/zshrc ~/.zshrc

# Distribution specific setup
if [[ "$OSTYPE" == "darwin"* ]]; then # MacOS
   # Install Homebrew
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
   brew update
   brew install screenfetch fortune cowsay lolcat rbenv ruby python3
elif [[ "$OSTYPE" == "linux-gnu" ]]; then # Linux
   ln -s ~/dotfiles/bash/DIR_COLORS ~/.dir_colors
   ln -s ~/dotfiles/bash/Xresources ~/.Xresources
fi
