#!/bin/sh

# Unlink all symbolic links
unlink ~/.vimrc
unlink ~/.vim/syntax/coffee.vim
unlink ~/.vim/ftdetect/coffee.vim
unlink ~/.vim/after/ftplugin/python.vim
unlink ~/.vim/autoload/plug.vim

unlink ~/.bash_profile
unlink ~/.bashrc

if [[ "$OSTYPE" == "darwin"* ]]; then # MacOS
   # Remove Homebrew entirely
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
elif [[ "$OSTYPE" == "linux-gnu" ]]; then # Linux
   unlink ~/.dir_colors
   unlink ~/.Xresources
fi
