# Environment Variables
if [[ "$OSTYPE" == "darwin"* ]]; then # MacOS
   export PATH=$PATH:$HOME/Library/Android/sdk/platform-tools

   # Graphics env variables
   export GLM_INCLUDE_DIR=/usr/local/Cellar/glm/0.9.8.1/include
   export GLFW_DIR=$HOME/open-source-bin/glfw-3.2.1
   export GLEW_DIR=/usr/local/Cellar/glew/2.0.0

   # Audio Api Variables
   export FMOD_DIR=$HOME/open-source-bin/FMOD_API

   # Custom Python3 Paths
   export PYTHONPATH=${PYTHONPATH}:$HOME/Projects/SearchEngine/

   # OpenSSL env vars since OSX is phasing it out. These depend on Homebrew.
   export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include
   export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib
   #export DEP_OPENSSL_INCLUDE=`brew --prefix openssl`/include

   # Export the Java path if available, haven't found a better way to do it
   export JAVA_HOME=`/usr/libexec/java_home`
elif [[ "$OSTYPE" == "linux-gnu" ]]; then # Linux
   :
fi

export PATH="$HOME/.cargo/bin:$PATH"

# Path to oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Theme and theme configurations
ZSH_THEME="spaceship"

# Spaceship theme configurations
# Prompt
SPACESHIP_PROMPT_SEPARATE_LINE=false
SPACESHIP_BATTERY_SHOW=false

# Directory
SPACESHIP_DIR_TRUNC=1
SPACESHIP_DIR_TRUNC_REPO=false

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Plugins for ZSH
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Aliases
# For a full list of active aliases, run `alias`.
# Cal Poly Servers
# Unix 1-4 are 64-Bit Servers
alias calpolyU1="ssh jcatanio@unix1.csc.calpoly.edu"
alias calpolyU2="ssh jcatanio@unix2.csc.calpoly.edu"
alias calpolyU3="ssh jcatanio@unix3.csc.calpoly.edu"
alias calpolyU4="ssh jcatanio@unix4.csc.calpoly.edu"
# Unix 5 is a 32-Bit Server
alias calpolyU5="ssh jcatanio@unix5.csc.calpoly.edu"
# JSON formatting utility
alias prettyjson="python3 -m json.tool"
#
# Distribution specific definitions
if [[ "$OSTYPE" == "darwin"* ]]; then # MacOS
   # Wifi alias on/off
   WIFI_PORT='en0'
   alias wifi="networksetup -setairportpower $WIFI_PORT"
elif [[ "$OSTYPE" == "linux-gnu" ]]; then # Linux
   :
fi

# Startup commands
if [[ "$OSTYPE" == "darwin"* ]]; then # MacOS
   eval "$(rbenv init -)"
fi

# Optional startup commands
#screenfetch -E
#fortune | cowsay -f moose | lolcat
