# Variables
WIFI_PORT='en0'

alias ls='ls -FG'

# Server Alias's
# Unix 1-4 are 32-Bit Servers
alias calpolyU1='ssh jcatanio@unix1.csc.calpoly.edu'
alias calpolyU2='ssh jcatanio@unix2.csc.calpoly.edu'
alias calpolyU3='ssh jcatanio@unix3.csc.calpoly.edu'
alias calpolyU4='ssh jcatanio@unix4.csc.calpoly.edu'
# Unix 11-14 are 64-Bit Servers
alias calpolyU11='ssh jcatanio@unix11.csc.calpoly.edu'
alias calpolyU12='ssh jcatanio@unix12.csc.calpoly.edu'
alias calpolyU13='ssh jcatanio@unix13.csc.calpoly.edu'
alias calpolyU14='ssh jcatanio@unix14.csc.calpoly.edu'

# Wifi alias on/off
alias wifi="networksetup -setairportpower $WIFI_PORT"

# Colors
export LSCOLORS=gxBxhxDxcxhxhxhxhxcxcx
