# Variables
WIFI_PORT='en0'

# NOTE: --color may not be necessary for Mac OS X
alias ls='ls -FG'

# Server Alias's
# Unix 1-4 are 64-Bit Servers
alias calpolyU1='ssh jcatanio@unix1.csc.calpoly.edu'
alias calpolyU2='ssh jcatanio@unix2.csc.calpoly.edu'
alias calpolyU3='ssh jcatanio@unix3.csc.calpoly.edu'
alias calpolyU4='ssh jcatanio@unix4.csc.calpoly.edu'
# Unix 5 is a 32-Bit Server
alias calpolyU5='ssh jcatanio@unix5.csc.calpoly.edu'

# Wifi alias on/off
alias wifi="networksetup -setairportpower $WIFI_PORT"

# JSON formatting utility
alias prettyjson="python3 -m json.tool"

# Colors
# Uncomment for Mac OS X
export LSCOLORS=gxBxhxDxcxhxhxhxhxcxcx

# On linux set up dir_colors symlink and this will use it if it finds one.
#if [ -f ~/.dir_colors ]; then
#   eval `dircolors ~/.dir_colors`
#fi

# Transfer script alias, input path.
alias transfer="/Users/JonCatanio/Projects/Utility\ Tools/SSH\ Scripts/transfer"
