# Variables
WIFI_PORT='en0'

# NOTE: --color may not be necessary for Mac OS X
alias ls='ls -FG --color'

# Server Alias's
# Unix 1-4 are 32-Bit Servers
alias calpolyU1='ssh jcatanio@unix1.csc.calpoly.edu'
alias calpolyU2='ssh jcatanio@unix2.csc.calpoly.edu'
alias calpolyU3='ssh jcatanio@unix3.csc.calpoly.edu'
alias calpolyU4='ssh jcatanio@unix4.csc.calpoly.edu'
# Unix 11-14 are 64-Bit Servers
alias calpolyU11='ssh jcatanio@unix11.csc.calpoly.edu'
alias calpolyU12='ssh jcatanio@unix12.csc.calpoly.edu'
alias calpolyU13='ssh jcatanio@unix13.csc.calpoly.edu'
alias calpolyU14='ssh jcatanio@unix14.csc.calpoly.edu'

# Wifi alias on/off
alias wifi="networksetup -setairportpower $WIFI_PORT"

# Colors
# Uncomment for Mac OS X
#export LS_COLORS=gxBxhxDxcxhxhxhxhxcxcx

# On linux set up dir_colors symlink and this will use it if it finds one.
if [ -f ~/.dir_colors ]; then
   eval `dircolors ~/.dir_colors`
fi

# Transfer script alias, input path.
alias transfer=""
